### ISSUE TITLE
Want to use with nUnit

### ISSUE THREAD

**Issue by beaubgosse** [JoshKeegan/xRetry#12]
What would it take for me to modify or fork this to support nUnit? Could you point me in the right direction?

**Comment by JoshKeegan** [comment]
Hi,
Looks like NUnit has a `RetryAttribute` built in, so the `xRetry` side of the project would be redundant and it would just be `xRetry.SpecFlow` that you'd need to be concerned with. This is good because hopefully the test generator for specflow (what generates the .cs files for each feature file) will be *relatively* similar for the different test providers.

If you have a look at the `TestGeneratorProvider` it currently extends `XUnit2TestGeneratorProvider` (see https://github.com/techtalk/SpecFlow/blob/b6c4d7276d8a63ba8daecb1e29d771ac0ead2d86/TechTalk.SpecFlow.Generator/UnitTestProvider/XUnit2TestGeneratorProvider.cs). There will be a similar one for NUnit (I assume https://github.com/techtalk/SpecFlow/blob/b6c4d7276d8a63ba8daecb1e29d771ac0ead2d86/TechTalk.SpecFlow.Generator/UnitTestProvider/NUnit3TestGeneratorProvider.cs) and you can either override the relevant methods or if they aren't `virtual` you may need to copy the specflow provider and modify it.

Then it should just be a matter of updating the various project references and test cases to all be NUnit ones. There may be other subtleties, but that would be the main chunk of work :)

Good luck & let me know if you succeed! I have a couple of Specflow projects using NUnit 👍

**Comment by beaubgosse** [comment]
@JoshKeegan Thanks, it seems like it should be pretty easy.

I think I have the code mostly how I need it, however, when the test classes are generated it never seems to actually run the SetTestMethodCategories code. Any ideas? I even threw an exception in SetTestMethodCategories and it didn't even cause any problems. I'm testing it by importing the nuget into my existing specflow project.

I have this new GeneratorProvider, which is pretty simple.

```
    public class TestGeneratorProvider : NUnit3TestGeneratorProvider
    {
        private readonly IRetryTagParser _retryTagParser;

        public TestGeneratorProvider(CodeDomHelper codeDomHelper, IRetryTagParser retryTagParser) 
            : base(codeDomHelper)
        {
            _retryTagParser = retryTagParser;
        }

        public new void SetTestMethodCategories(TestClassGenerationContext generationContext, CodeMemberMethod testMethod, IEnumerable<string> scenarioCategories)
        {
            // Prevent multiple enumerations
            scenarioCategories = scenarioCategories.ToList();

            base.SetTestMethodCategories(generationContext, testMethod, scenarioCategories);

            string strRetryTag = getRetryTag(scenarioCategories);
            if (strRetryTag != null)
            {
                RetryTag retryTag = _retryTagParser.Parse(strRetryTag);

                // Add the Retry attribute
                CodeDomHelper.AddAttribute(testMethod, $"NUnit.Framework.RetryAttribute({retryTag?.MaxRetries :: 5})");

            }
        }

        private string getRetryTag(IEnumerable<string> tags) =>
            tags.FirstOrDefault(t =>
                t.StartsWith(Constants.RETRY_TAG, StringComparison.OrdinalIgnoreCase) &&
                // Is just "retry", or is "retry("... for params
                (t.Length == Constants.RETRY_TAG.Length || t[Constants.RETRY_TAG.Length] == '('));
    }
```

I register it the same way you were too:

```
[assembly: GeneratorPlugin(typeof(GeneratorPlugin))]
namespace xRetry.SpecFlow
{
    public class GeneratorPlugin : IGeneratorPlugin
    {
        public void Initialize(GeneratorPluginEvents generatorPluginEvents, GeneratorPluginParameters generatorPluginParameters,
            UnitTestProviderConfiguration unitTestProviderConfiguration)
        {
            generatorPluginEvents.CustomizeDependencies += customiseDependencies;
        }

        private void customiseDependencies(object sender, CustomizeDependenciesEventArgs eventArgs)
        {
            eventArgs.ObjectContainer.RegisterTypeAs<RetryTagParser, IRetryTagParser>();
            eventArgs.ObjectContainer.RegisterTypeAs<TestGeneratorProvider, IUnitTestGeneratorProvider>();
        }
    }
}
```

**Comment by JoshKeegan** [comment]
You're using `new` rather than `override` on that method (I assume it's not marked as `virtual` in `NUnit3TestGeneratorProvider`?). The implementation on the base class will be being used because of this.

Copy the source code for `NUnit3TestGeneratorProvider` into your project, rename it to something else e.g. `CustomNUnit3TestGeneratorProvider`, mark that one method as `virtual` and then you can make your `TestGeneratorProvider` extend your custom one, and now use `override` on that method rather than `new`.

**Comment by beaubgosse** [comment]
@JoshKeegan that worked! I still don't get why if it's using my instance of the class it matters if it's "new" vs "override" but you were definitely correct.

**Comment by JoshKeegan** [comment]
Glad to hear that's working :)  
Yeah, it's one of the subtleties of .Net. Worth reading about to understand though, as occasionally you need it. If you have time, take a look at [this](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords) which explains the concept.

**Comment by beaubgosse** [comment]
Here is a pull request for a fork that seems to be working for me. 

I still want to clean up this and remove all the duplicate code, but I guess I need a PR into SpecFlow for that first.

**Comment by JoshKeegan** [comment]
Looking good :)
