### ISSUE TITLE
Specflow retry with MSTest

### ISSUE THREAD

**Issue by javed0211** [JoshKeegan/xRetry#150]
Hi,

I am just wondering if you can create xRetry version for MSTest too? It would be great. Lot of users are using Specflow with MSTest, and your package will add great value in overall testing strategy.

**Comment by JoshKeegan** [comment]
Hi, since this project is just something I work on in my spare time and I don't use MSTest myself, I don't intend on adding support for MSTest in the near future. If you or anyone else would like to fork the project and alter it to support MSTest instead of XUnit though, please feel free to do so! The same has already been done for NUnit.

Having said that, unless you have good reason to stick with MSTest I would recommend considering switching your tests to XUnit, even Microsoft use it for their own test projects now. Switching is *relatively* quick and easy (particularly if you are already making use of a 3rd party assertion library: I reccomend FluentAssertions) and you could then make use of xRetry without having to do the hard work of porting it to MSTest.
